---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echoinfo-dev
  chart:
    git: git@github.com:Atomizer99/GitOps-eli
    path: charts/echo
    ref: master
  values:
    image:
      repository: gcr.io/echo-project-320612/echo
      tag: dev-hdtwcel9
    replicaCount: 1
    hpa:
      enabled: false
