---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echoinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echoinfo-rc
  chart:
    git: git@github.com:Atomizer99/GitOps-eli
    path: charts/echo
    ref: master
  values:
    image:
      repository: gcr.io/echo-project-320612/echo
      tag: stg-9ij63o4c
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
